---
deployment:
  tasks:
    - export DEPLOYPATH=/home/lichenpr/public_html/
    - /bin/cp -f index.html $DEPLOYPATH
    - /bin/cp -f onboarding-questionnaire.html $DEPLOYPATH
    - /bin/cp -f thank-you.html $DEPLOYPATH
    - /bin/cp -f feedback-thank-you.html $DEPLOYPATH
    - /bin/cp -f README.md $DEPLOYPATH
